version: '3.9'

networks:
  inventory:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    volumes: 
      -  ./App:/var/www/html
    ports:
      - "9000:80"
      - "4443:443"
    networks:
      - inventory

  mariadb:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/database:/var/lib/mysql:rw
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    networks:
      - inventory
